# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeeTo_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'XLPagerTabStrip', '~> 8.1'
	pod 'Apollo', '~> 0.9.4'
	pod 'UITextView+Placeholder'

  # Pods for SeeTo_IOS

  target 'SeeTo_IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeeTo_IOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
